### ISSUE TITLE
Automatic cache clearing with ``lru_cache``'s ``maxsize``

### ISSUE THREAD

**Issue by Pierre-Sassoulas** [pylint-dev/astroid#1150]
Following https://github.com/PyCQA/astroid/pull/1139, it's not possible to clear the cache. We did not use ``lru_cache`` because the current implementation only uses the first argument as key (because the other one is context?), and lru_cache does not allow that.

In order to use ``lru_cache`` we need to ask ourselves if is it right that inference tip functions always take exactly two arguments -- a node and a context? If so, what is context exactly? Does it remain constant during an inference session? Is it fine to hash it via id()?

See original comment by @superbobry [here](https://github.com/PyCQA/astroid/pull/1139#discussion_r693555590) and [here](https://github.com/PyCQA/astroid/pull/1139#issuecomment-905906350)

### Current behavior

The cache can be cleared with an API.

### Expected behavior

Automatic clearing when the cache increase above a set value (configurable ?).

**Comment by jacobtylerwalls** [comment]
Reopening because #1565 will likely be reverted.

**Comment by jacobtylerwalls** [comment]
The interface for clearing astroid's various caches is `astroid.MANAGER.clear_cache()`. If we missed one, please open a new issue and provide details. Thanks all!
