### ISSUE TITLE
Improve descriptions for binary operations

### ISSUE THREAD

**Issue by elfring** [pylint-dev/astroid#1214]
### Story

[Binary operations are mentioned in the software documentation](https://greentreesnakes.readthedocs.io/en/latest/nodes.html#BinOp "Documentation for binary operations").
Information is provided that binary operations would be involved also for [comparisons](https://greentreesnakes.readthedocs.io/en/latest/nodes.html#Compare "Documentation for comparisons").
:thought_balloon: Thus I propose to improve descriptions for this relationship.

### Version
2.8.4

**Comment by DanielNoord** [comment]
What is actually missing from the current documentation? I guess you are referring to these [docs](https://pylint.pycqa.org/projects/astroid/en/latest/api/astroid.nodes.html#astroid.nodes.BinOp)? If not, please be much more specific.

Btw, excuse me if I assume wrongly, but I feel English is not your main language and saw on your profile you did some projects in French. Perhaps if you feel more comfortable explaining your suggestion in French for **this issue** it might be best to do so. That might actually improve the communication and resolve this issue seeing as some of your recent discussions with Pierre have been quite convoluted...

**Comment by elfring** [comment]
>I guess you are referring to these [docs](https://pylint.pycqa.org/projects/astroid/en/latest/api/astroid.nodes.html#astroid.nodes.BinOp)?

Yes. (in principle)

I linked to corresponding information in the representation from “Read the Docs” for this clarification approach.


>… saw on your profile you did some projects in French. …

I am obviously trying to achieve something for several software components also by international collaboration.


>… That might actually improve the communication …

I suggest to clarify the documentation another bit for [the safe usage of binary operations](https://docs.python.org/3/reference/expressions.html#binary-arithmetic-operations "Documentation for expressions in Python") by the means of the astroid programming interface.
* Comparisons
* Computations

**Comment by DanielNoord** [comment]
> Each of the linked information sources present documentation style alternatives.
> 
> I am looking especially on possibilities to distinguish the expression (or operation) categories clearly.

You can do that by using the `op` attribute of each `BinOp` node. This distinguishes among the different operators.

> > in what way is the current "API usage" unsafe?
> 
> Incomplete software documentation triggers undesirable development side effects, doesn't it?

Yes, but I wouldn't necessarily call it unsafe. Then again, I wil rephrase: in what way is the current documentation incomplete?

> > And in what way is it inconvenient?
> 
> I imagine that derived classes could provide type safety and helpful methods.

Which derived class would you need? The `op` attribute allows you to distinguish amongst operation types and helper functions can be written with the knowledge that all `BinOp` nodes will have the same attributes and methods.
If you want to write a helper function that is only useful for the `+` operator you can just do:
```python
def helper(node: nodes.BinOp) -> None:
    if not node.op == "+":
        return
    # your helper function
```
This is not really different from having to do:
```python
def derived_class_creator(node: nodes.BinOp) -> None:
    if node.op == "+":
        derived = DerivedAdditionClass(node)
        derived.helper()
```

**Comment by elfring** [comment]
>I don't understand what you mean, I'm sorry!

I am looking at this software place where you might know the corresponding development history better (than me).


>Why would we need to expose that method, which seems only relevant for that checker, to all users of BinOp?

I imagine that more checks can benefit from a general distinction.


>What do you mean with "operation categories"?

* Computations
* Comparisons

**Comment by DanielNoord** [comment]
> I am looking at this software place where you might know the corresponding development history better (than me).

Ah! Oh, I only "joined" this project recently. In fact, I have focused much of my attention on adding more typing to the codebase which should help new contributors such as yourself to get a better grasp of it.

> I imagine that more checks can benefit from a general distinction.

I don't see why atm. If we have a check that suggest using augmented assignment why would other checkers need access to that information as well?
And even if I am incorrect, I would suggest to move that function to the `utils` module of `pylint` which houses all functions relevant for multiple checkers that do not concern direct inference (as the latter should go in `astroid`).

> * Computations
> * Comparisons

You keep repeating the same answers, which I must say is does not help the process of getting to the bottom of what you exactly want. Therefore, let me be more specific myself and please try to answer the following answers as expressively as you can!

1) Which "operations" of the "Computations" category are not covered by the `BinOp` node?

2) For these "operations",  are they also not covered by other `astroid` nodes?

3) Which "operations" belonging to the "Comparisons" category are not covered by the `Compare` node?

4) For these "operations", are they covered by other nodes? Perhaps the `BinOp` node?

5) What specific element of inference are we currently missing in the "ast representation" created by `astroid` for "operations" of the "Computations" and "Comparison" categories?

6) Can you give an example of "future use case"? I fail to which future use cases are not currently covered by our inference of `BinOp` nodes?

7) How would you distinguish the "operations" of the "Computations" and "Comparison" categories from the ones currently covered by `BinOp`?
