### ISSUE TITLE
Wrong type inferred - inference type cache is missing context

### ISSUE THREAD

**Issue by kriek** [pylint-dev/astroid#1828]
Moving discussion started in https://github.com/PyCQA/pylint/issues/7464 to astroid repo.

### Steps to reproduce

```
import astroid

result1, result2 = astroid.extract_node("""
class Base:
    def return_type(self):
        return type(self)()

class A(Base):
    def method(self):
        return self.return_type()

class B(Base):
    def method(self):
        return self.return_type()

A().method()  #@
B().method()  #@
""")

print(next(result1.infer()))
print(next(result2.infer()))
```

### Current behavior
Instance of .A
Instance of .A

### Expected behavior
Instance of .A
Instance of .B

### Workaround
Modify inference_tip.py to disable cache in _inference_tip_cached function. 

### `python -c "from astroid import __pkginfo__; print(__pkginfo__.version)"` output
2.13.0-dev0

**Comment by kriek** [comment]
Timing the pylint evaluation of checkers/ folder from pylint repo, I don't see a big difference with and without (explicit raise KeyError inserted) the cache:
with:
```
real    0m57.994s
real    0m58.089s
real    0m57.446s
real    0m57.366s
```
without:
```
real    0m58.913s
real    0m58.693s
real    0m59.070s
real    0m58.799s
```

**Comment by DanielNoord** [comment]
Would you want to create a PR to remove it?

**Comment by kriek** [comment]
Yes, will do.
