### ISSUE TITLE
sdist is missing tox.ini and resources.py

### ISSUE THREAD

**Issue by mtelka** [pylint-dev/astroid#2129]
The sdist package at PyPI is missing both `tox.ini` and `tests/resources.py` files (and maybe few others).  Without these files testing fails.  Please note that all `tests/test_*` files are properly included in the sdist package.  Please add missing files to sdist to make testing working.  Thank you.

**Comment by Pierre-Sassoulas** [comment]
I'm not sure we should include the tests in the packaging, almost no one use it [citation required] and this add to the download size / time.

**Comment by mtelka** [comment]
Tests are already there.  Only few files are missing.  The complete github tarball is ca 450 kB, while sdist is ca 350 kB.  Everybody can afford +100 kB of download size / time these days :-).  Thanks.

**Comment by jacobtylerwalls** [comment]
I think this is a reasonable request. I skimmed this [thread](https://discuss.python.org/t/should-sdists-include-docs-and-tests/14578), and it looks like views range from ambivalence to gently encouraged.

**Comment by mtelka** [comment]
It looks like the complete list of missing files for tests is this:
```
requirements_test_brain.txt
requirements_test.txt
requirements_test_min.txt
requirements_test_pre_commit.txt
tests/__init__.py
tests/resources.py
tox.ini
```
