### ISSUE TITLE
3.0.0 release plan

### ISSUE THREAD

**Issue by Pierre-Sassoulas** [pylint-dev/astroid#2148]
- [x] Drop Python 3.7 in astroid + pylint (can be done independently on one another - i.e. we don't need a new astroid release to merge https://github.com/pylint-dev/pylint/pull/8609)
- [x] Move all the issues from astroid 2.16.0 in astroid 3.0
- [x] Update changelog
- [x] Release astroid 3.0.0a0
- [x] Do additional breaking changes, cleanup, and fix bugs, e.g. remove cachedproperty, change TryExcept and TryFinally to just Try
    - https://github.com/pylint-dev/astroid/pull/1867, changes to the Import nodes
    - https://github.com/pylint-dev/astroid/issues/1338
    - https://github.com/pylint-dev/astroid/issues/1868
- [x] After each major change release new alpha for astroid
- [x] For pylint 3.0 beta: Update pinned astroid version to use latest alpha release
- [x] Once everything works and most/all of the changes are done -> release astroid 3.0

While doing this: Continue to release new pylint 3.0 alpha or beta releases so we can gather feedback

**Comment by jacobtylerwalls** [comment]
Looks like the punchlist is done, since we don't have consensus on #1338.

I'd like to bump astroid to 3.0 beta this weekend unless anyone has last-minute changes they want to get in?

**Comment by Pierre-Sassoulas** [comment]
I think if we want to release pylint by 2023-10-02 we'll need to release astroid 3.0.0 sometime in the middle of next week. I don't think a lot of persons are using astroid alphas or betas (? -- but I can't check that for sure because pypystats does not give this information and I can't use Google's big-query), so imo we could even release astroid 3.0.0 now (or possibly after pylint beta does not fail spectacularly in the wild).

**Comment by DanielNoord** [comment]
Let's release! We can always do a 4.x 😁

**Comment by jacobtylerwalls** [comment]
Done!

**Comment by Pierre-Sassoulas** [comment]
Sweaty hands when actually clicking that release button (for no reasons as we released a half dozen alpha, but it's still a **major**).
