### ISSUE TITLE
astroid depends on 'crypt', which is removed in Python 3.13

### ISSUE THREAD

**Issue by limburgher** [pylint-dev/astroid#2327]
Still present in git and 3.0.1.
https://bugzilla.redhat.com/show_bug.cgi?id=2246054

According to https://docs.python.org/3.13/whatsnew/3.13.html:

PEP 594: Remove the crypt module and its private _crypt extension, deprecated in Python 3.11.
The hashlib module is a potential replacement for certain use cases.
Otherwise, the following PyPI projects can be used:
- bcrypt: Modern password hashing for your software and your servers.
- passlib: Comprehensive password hashing framework supporting over 30 schemes.
- argon2-cffi: The secure Argon2 password hashing algorithm.
- legacycrypt: Wrapper to the POSIX crypt library call and associated functionality.
(Contributed by Victor Stinner in gh-104773.)

**Comment by DanielNoord** [comment]
Hi, the link you provided doesn't work sadly.

I also don't see how we are depending on `crypt`. We don't import it and only provide a `brain`.
Please open a PR to fix this issue to show us what we would need to change. Closing for now as I don't see any immediate action on our side.

**Comment by limburgher** [comment]
I've fixed the link. The tests fail as a result of crypt's removal.

**Comment by DanielNoord** [comment]
Ah my bad, I was too quick to close.

https://github.com/pylint-dev/astroid/blob/7124000a60da610010be25990132a087313fc5c6/tests/brain/test_brain.py#L1980

We need to disable the test defined here for `3.13+`. Should be an easy fix, contribution very much welcomed!

**Comment by limburgher** [comment]
I'll take a look. Note there are two additional tests failing.
