### ISSUE TITLE
Backstory behind license being LGPL?

### ISSUE THREAD

**Issue by tony** [pylint-dev/astroid#2337]
Hi! Thank you for the project! Sorry for the non-technical issue.

_Context: I am a downstream package user using [sphinx-autodoc2](https://github.com/sphinx-extensions2/sphinx-autodoc2)._

In regards to license being LGPL v2.1: are there any places where there's been prior conversations or context behind it?

In either case, what are the project's reasoning behind LGPL in the here and now? e.g. Reciprocity in terms of contributions, etc.

The reason I bring this up is as a downstream maintainer of MIT licensed python packages, it's easier for me to incorporate BSD / MIT / ISC / Apache 2 packages.  LGPL is more complex: it has more places where complication can happen that's not related to any technical detail (e.g. Was a derivitive work created when X situation happened). It shifts too much compliance burden (I think?) downstream to fellow open source packages.

Thoughts? It looks like LGPL is pretty well established in the package already.

**Comment by Pierre-Sassoulas** [comment]
This is a decision taken by Logilab and Logilab's employee 20 years ago that there's no way to reasonably change at this point.
