### ISSUE TITLE
Pylint checks against incorrect type with properties that have a getter and setter

### ISSUE THREAD

**Issue by here-abarany** [pylint-dev/astroid#2467]
### Steps to reproduce

1. Install pylint 3.2.5 with astroid 3.2.3
2. Set up a Python script with the following code:
    ```python
   class Point:
       def __init__(self, x: float, y: float):
           self._x = x
           self._y = y

       @property
       def x(self) -> float:
           return self._x

       @x.setter
       def x(self, x: float):
           self._x = x

       @property
       def y(self) -> float:
           return self._y

       @y.setter
       def y(self, y: float):
           self._y = y

   test = Point(1.2, 3.4)
   value_neg = -test.x
   ```
4. Run pylint 

### Current behavior

The following error is emitted: E1130: bad operand type for unary -: Point (invalid-unary-operand-type)

### Expected behavior

pylint reports no errors

### `python -c "from astroid import __pkginfo__; print(__pkginfo__.version)"` output

3.2.3

**Comment by here-abarany** [comment]
For now I can work around the issue without explicitly pinning the package by excluding the buggy version in requirements.txt. (`astrid!=3.2.3`)

**Comment by jacobtylerwalls** [comment]
Thanks for the report. Just a heads up that the mix might turn out to be in pylint, so it's too early to know if the pin you suggest will be the one you eventually desire.
