### ISSUE TITLE
Update OSS-Fuzz integration

### ISSUE THREAD

**Issue by correctmost** [pylint-dev/astroid#2511]
## Description

An OSS-Fuzz integration was [set up for astroid](https://github.com/google/oss-fuzz/pull/10039) last year.  The build has been [failing for a few months](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=69185) and it seems to lack active maintenance.

Would you mind if I fixed the build and assigned myself as a co-maintainer?  I [maintain the librsvg integration](https://github.com/google/oss-fuzz/tree/master/projects/librsvg) and I am familiar with the OSS-Fuzz platform.

Having a functioning OSS-Fuzz integration could help catch regressions on the `main` branch before releases are tagged.

### Action items
1. Fix the build by pinning the version to astroid 3.2.4 for now
    - The OSS-Fuzz images are currently stuck on Python 3.8, but there is work being done to [support 3.10
](https://github.com/google/oss-fuzz/pull/12027)
    - Fixing the build now will allow the corpus to grow, which will benefit future runs against `main` (once Python 3.10 support lands)
1. Add myself to the list of people who are automatically CC'd on astroid bug reports

### Considerations
1. Are any of the current maintainers interested in being set as the primary contact for the OSS-Fuzz integration?
    - To get full access to the system, you will need a Google/Gmail account
        - Note: The associated email address will be listed in the OSS-Fuzz repo without any obfuscation ([example](https://github.com/google/oss-fuzz/blob/master/projects/librsvg/project.yaml))
    - Other maintainers can also be automatically CC'd, but there can only be one primary
1. OSS-Fuzz can generate a decent amount of bug reports
    - I can help triage the issues, but some maintainers do not want to get notifications from a totally [separate system](https://bugs.chromium.org/p/oss-fuzz/issues/list?q=label%3AProj-astroid&can=1)
1. Updating the [astroid project files](https://github.com/google/oss-fuzz/tree/master/projects/astroid) on OSS-Fuzz requires the signing of a Google CLA
    - I have already signed the CLA, so I can help with PRs if you are uncomfortable with that process
1. Google offers [monetary rewards](https://bughunters.google.com/about/rules/open-source/5097259337383936/oss-fuzz-reward-program-rules#fuzzing-coverage) for improving the code coverage of existing integrations.  I am interested in fixing the build and helping maintain the integration independently of that, but I also have ideas for increasing coverage that might qualify for said rewards.

Google has [documentation for the OSS-Fuzz system](https://google.github.io/oss-fuzz/), but I can also help answer any questions.  Thanks!

**Comment by jacobtylerwalls** [comment]
Thanks for this @correctmost, I'll ask around and get an answer on the primary contact, but I anticipate that the answers to your other questions will be "for sure".

**Comment by jacobtylerwalls** [comment]
I got a response from @Pierre-Sassoulas that it's okay to list me (@jacobtylerwalls) as primary: jacobtylerwalls [ at ] gmail.com

> Would you mind if I fixed the build and assigned myself as a co-maintainer?

Yes, go ahead, and thanks for the help!

**Comment by jacobtylerwalls** [comment]
Thank you!
