### ISSUE TITLE
Remove code related to old-style classes

### ISSUE THREAD

**Issue by akamat10** [pylint-dev/astroid#2560]
To simplify the astroid, shall we get rid of code in the repo related to old-style classes? This is tied to python 2.x and is no longer relevant. This will simplify the code base, improve maintainability and perhaps even have some performance improvements. [ClassDef](https://github.com/pylint-dev/astroid/blob/main/astroid/nodes/scoped_nodes/scoped_nodes.py#L1833) class is most affected by it. Happy to work on this.

**Comment by DanielNoord** [comment]
I'd be okay with it, seems like a nice improvement.

@Pierre-Sassoulas Do you agree?

**Comment by Pierre-Sassoulas** [comment]
Yeah, sounds good !
