### ISSUE TITLE
Cannot import 'rti.connextdds' due to 'invalid syntax (rti.connextdds, line 18332)' (syntax-error)

### ISSUE THREAD

**Issue by jpsamper2009** [pylint-dev/astroid#2640]
Hello! I would like to bring up this bug report from `pylint` https://github.com/pylint-dev/pylint#9585:

From what I gather, the version of `astroid` was bumped from `2.15.1` to `3` between `v3.0.0a6` and `v3.0.0a7` of `pylint`. 

Since `astroid` is responsible for throwing the exception that displays the syntax error message (https://github.com/pylint-dev/pylint/blob/68cb5b320653ad64c68ff48a4bb4ba449a01d3a6/pylint/lint/pylinter.py#L980-L990), my guess is that the underlying bug is here and not in `pylint`.

**Comment by jacobtylerwalls** [comment]
Thanks for the report, but at the moment we need the underlying source to verify whether there is or isn't a syntax error as pylint currently reports. We can continue on the pylint issue 👍

**Comment by jzenoz** [comment]
The underlying source was provided here btw:
https://github.com/pylint-dev/pylint/issues/9585#issuecomment-2518017352

**Comment by jzenoz** [comment]
Not sure if this should be reopened as well @jacobtylerwalls

**Comment by jzenoz** [comment]
[__init__.zip](https://github.com/user-attachments/files/19618309/__init__.zip)
