### ISSUE TITLE
astroid.modutils.load_module_from_file failing on symlinks outside of sys.path

### ISSUE THREAD

**Issue by mariocj89** [pylint-dev/astroid#538]
###### 1. Create a file outside of your path and symlink it to CWD:
```python3
import sys
import os
import tempfile
import pathlib

tmp_dir = tempfile.mkdtemp()
linked_path = pathlib.Path()
original_path = pathlib.Path(tmp_dir)

filename = 'pfile.py'
original_file = original_path / filename
linked_file = linked_path / filename

with open(original_file, 'w') as f:
    f.write("x=1;print(x)")
os.remove(linked_file)
os.symlink(original_file, linked_file)
```
(just run this once once)

###### 2. Try to import the file with `load_module_from_file`
```
astroid.modutils.load_module_from_file("pfile.py")
```

This will raise ```ImportError: Unable to find module for <full_path_in_tmpdir>/pfile.py in```
Note it is fine to do just ```import pfile```

### Current behaviour
`load_module_from_file` raises ImportError  when importing a file symlinked from a folder out of `sys.path`.

### Expected behaviour
It should be fine to import a module even if it is symlinked from a non-path folder.

### Version information
Present in the latest versions of 1.6 and 1.5: 1.6.3 and 1.5.3 
Works in the latest version of 1.4: 1.4.9

### Related commits/code
- Commit that introduced the issue: cda9dc4ad0e2cc075553d133dd0fdab468d614d7
- https://github.com/PyCQA/astroid/blob/8575ac1c0bd247bc314f6752355d1ea647dec911/astroid/modutils.py#L304 This check will fail as the folder of the symlinked file is not in sys.path

### Possible implementation

DISCLAIMER: Wihtout knowing much about the astroid my proposal might be total rubish.

If the objective of ```for path in six.moves.map(_canonicalize_path, sys.path):``` is just to verify that the file is within a valid path, have a function that does that, pass the original filename and check both the file with abspath and realpath.

Just checking abspath can cause an issue in the other direction, trying to import the symlink whilst having the realfile within the path (unless you are OK breaking that or what the commit was trying to address).

I am happy to get a PR through with the appropiate tests if this is confirmed to be something that needs fixing.

**Comment by mariocj89** [comment]
Glad to hear that :)

Does the "possible implementation" proposed seems reasonable?

Will prepare a PR for that

**Comment by PCManticore** [comment]
Sure thing, sounds reasonable, feel free to send a PR!
