### ISSUE TITLE
Enum value type inference is very limited

### ISSUE THREAD

**Issue by alexbecker** [pylint-dev/astroid#612]
Looking at https://github.com/PyCQA/astroid/commit/6f7d8014a3dd951b060c32dfef458aff3e18b0cf, it appears `Enum` `value` attribute type inference is limited only to literals. Unfortunately my company makes use of `Enum` subclasses with `tuple` values.

### Steps to reproduce
1. Create the following `test.py` file:
```python
import enum


class MyEnum(enum.Enum):
    a = (1, 2)


if __name__ == '__main__':
    for i in MyEnum.a.value:
        print(i)
    print(1 in MyEnum.a.value)
```
2. Run `pylint test.py`.

### Current behavior
```
************* Module test
test.py:9:13: E1133: Non-iterable value MyEnum.a.value is used in an iterating context (not-an-iterable)
test.py:11:15: E1135: Value 'MyEnum.a.value' doesn't support membership test (unsupported-membership-test)
```

### Expected behavior
No error should occur since `MyEnum.a.value` is a tuple.

### ``python -c "from astroid import __pkginfo__; print(__pkginfo__.version)"`` output
`2.0.4`

**Comment by PCManticore** [comment]
Thanks for creating an issue!

**Comment by alexbecker** [comment]
Thanks for tackling this! Excited for the next release.
